name: SuperSpleef
version: '1.0.2'
main: me.iamnany.superspleef.SuperSpleef
api-version: '1.21'
commands:
  spleef:
    description: 'Start a Spleef game'
    usage: '/spleef'
  loadschem:
    description: 'load arena'
    usage: '/loadschem'