spleef:
  world: world
  map:
    width: 50
    length: 50
    height: 10
  lobby:
    x: 0
    y: 100
    z: 0
  schematic_placement:
    x: 0
    y: 0
    z: 0
  kill_y_value: 0
  schematic_name: "mce"